POST http://localhost:1200/login
Content-Type: application/json

{
    "username" : "AdminMenkor",
    "password" : "AdminMenkor1."
}

###
GET http://localhost:1200/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbk1lbmtvciIsInJvbGVfaWQiOjEsImlhdCI6MTcwNTIzNTQyMywiZXhwIjoxNzA1MjQyNjIzfQ.LhQUD5WpiKZKv-9VES4kEdHJs-6_MNij77SVTBZo644

###
GET http://localhost:1200/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJnYXJ5ZmVyZGluYW5kMTUiLCJyb2xlX2lkIjoyLCJpYXQiOjE3MDUyMzgxNDksImV4cCI6MTcwNTI0NTM0OX0.ZM7hsGmEF8_VA0GwwsQ-h1fz73a2meJxQl4KrzdolWw

###
GET http://localhost:1200/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbk1lbmtvciIsInJvbGVfaWQiOjEsImlhdCI6MTcwNTIzNTQyMywiZXhwIjoxNzA1MjQyNjIzfQ.LhQUD5WpiKZKv-9VES4kEdHJs-6_MNij77SVTBZo644

###
GET http://localhost:1200/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJnYXJ5ZmVyZGluYW5kMTUiLCJyb2xlX2lkIjoyLCJpYXQiOjE3MDUyMzgxNDksImV4cCI6MTcwNTI0NTM0OX0.ZM7hsGmEF8_VA0GwwsQ-h1fz73a2meJxQl4KrzdolWw

###
GET http://localhost:1200/atribut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbk1lbmtvciIsInJvbGVfaWQiOjEsImlhdCI6MTcwNTI4NzUzOCwiZXhwIjoxNzA1Mjk0NzM4fQ.9cqcu5W6g_3UOJnurdS6cuaXa3CFQAqyfH1Wduwudxg

###
POST http://localhost:1200/tambahKadet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbk1lbmtvciIsInJvbGVfaWQiOjEsImlhdCI6MTcwNTMwMjEwNSwiZXhwIjoxNzA1MzA5MzA1fQ.goa0J85AWFxaCJijRtWHedTYyJFGuOIKfWL8mh22qrk

###
GET http://localhost:1200/jabatans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbk1lbmtvciIsInJvbGVfaWQiOjEsImlhdCI6MTcwNjQ5OTIxMSwiZXhwIjoxNzA2NTA2NDExfQ.vvOBaqfVbJz6G22DunGerRusv0ASYc_0q30MSx-MtKg

###
POST http://localhost:1200/kadet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJnYXJ5ZmVyZGluYW5kMTUiLCJyb2xlX2lkIjoyLCJpYXQiOjE3MDU0NTA5OTUsImV4cCI6MTcwNTQ1ODE5NX0.tQOjQDd2f3XikWLWGUo6EUFGotqKoJozJ1Xe6iUQd7o

###